### ISSUE TITLE
Bigfish 地址不对

### ISSUE THREAD

**Issue by yutingzhao1991** [umijs/docz-theme-umi#3]
![image](https://user-images.githubusercontent.com/1061968/57938802-81b8b100-78fb-11e9-82d6-1092a250f4c1.png)

另外我觉得这个应该做出一个配置更好

**Comment by afc163** [comment]
搞一个 Bigfish logo 好了，和 docz 对应。

**Comment by sorrycc** [comment]
已经是 logo 了。
